#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define TARGET_FPS 60
#define TARGET_FRAME_MS (1000 / TARGET_FPS)

#define MAX_ENEMIES 96
#define MAX_PROJECTILES 320
#define MAX_PARTICLES 512
#define MAX_OBSTACLES 8
#define MAX_UPGRADE_OPTIONS 3

#define PLAYER_START_HP 100.0f
#define PLAYER_BASE_SPEED 320.0f
#define PLAYER_BASE_DAMAGE 16.0f
#define PLAYER_BASE_FIRE_RATE 0.357f
#define PLAYER_BASE_PROJECTILE_SPEED 560.0f

#define GRAVITY 800.0f
#define PLAYER_JUMP_FORCE 400.0f
#define PLAYER_MAX_JUMP_HEIGHT 32.0f
#define GROUND_Y 550.0f

#define RUN_TIME_LIMIT 180.0f
#define WAVES_TO_WIN 6

#define DIFF_EASY_ENEMY_HP_MUL 0.86f
#define DIFF_NORMAL_ENEMY_HP_MUL 1.00f
#define DIFF_HARD_ENEMY_HP_MUL 1.25f

#define DIFF_EASY_ENEMY_DMG_MUL 0.82f
#define DIFF_NORMAL_ENEMY_DMG_MUL 1.00f
#define DIFF_HARD_ENEMY_DMG_MUL 1.24f

#define DIFF_EASY_ENEMY_FIRE_MUL 1.16f
#define DIFF_NORMAL_ENEMY_FIRE_MUL 1.00f
#define DIFF_HARD_ENEMY_FIRE_MUL 0.84f

#define DIFF_EASY_TIME_BONUS 40.0f
#define DIFF_NORMAL_TIME_BONUS 0.0f
#define DIFF_HARD_TIME_BONUS -25.0f

#define DIFF_EASY_WAVE_OFFSET -1
#define DIFF_NORMAL_WAVE_OFFSET 0
#define DIFF_HARD_WAVE_OFFSET 1

#define DIFF_EASY_SCORE_MUL 0.95f
#define DIFF_NORMAL_SCORE_MUL 1.00f
#define DIFF_HARD_SCORE_MUL 1.15f

#define DATA_FILE "assets/data/scoreboard.dat"
#define STATS_FILE "assets/data/stats.dat"
#define SETTINGS_FILE "assets/data/settings.dat"

#endif
