#ifndef CONFIGURACAO_H
#define CONFIGURACAO_H

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define GRAVIDADE 800.0f
#define ALTURA_CHAO 600.0f

#define TEMPO_LIMITE 180.0f
#define ONDAS_TOTAIS 10

#define JANELA_LARGURA 1280
#define JANELA_ALTURA 720

#define ALVO_FPS 60
#define ALVO_DELAY_FRAMES_MS (1000 / ALVO_FPS)

#define MAXIMO_INIMIGOS 96
#define MAXIMO_PROJETEIS 320
#define MAXIMO_PARTICULAS 512
#define MAXIMO_PLATAFORMAS 8
#define MAXIMO_OPCOES_UPGRADE 3

#define JOGADOR_INICIAL_VIDA 100.0f
#define JOGADOR_INICIAL_VELOCIDADE 320.0f
#define JOGADOR_INICIAL_VELOCIDADE_PROJETIL 560.0f
#define JOGADOR_INICIAL_TAXA_DISPARO 0.357f
#define JOGADOR_INICIAL_DANO 16.0f
#define JOGADOR_INICIAL_ACELERACAO_LATERAL 800.0f

#define JOGADOR_MAXIMO_ALTURA_PULO 32.0f
#define JOGADOR_MAXIMO_ACELERACAO_LATERAL 1800.0f

#define JOGADOR_FORCA_PULO 400.0f

#define DIFICULDADE_FACIL_MULTIPLICADOR 0.8f
#define DIFICULDADE_NORMAL_MULTIPLICADOR 1.0f
#define DIFICULDADE_DIFICIL_MULTIPLICADOR 1.2f

#define DIFICULDADE_FACIL_AJUSTE_TEMPO_LIMITE 40.0f
#define DIFICULDADE_NORMAL_AJUSTE_TEMPO_LIMITE 0.0f
#define DIFICULDADE_DIFICIL_AJUSTE_TEMPO_LIMITE -40.0f

#define DIFICULDADE_FACIL_AJUSTE_ONDAS_MAXIMAS -2
#define DIFICULDADE_NORMAL_AJUSTE_ONDAS_MAXIMAS 0
#define DIFICULDADE_DIFICIL_AJUSTE_ONDAS_MAXIMAS 2

#define MISSIL_GUIANCA_LAG 0.15f
#define MISSIL_GUIANCA_APN_GANHO 3.0f
#define MISSIL_GUIANCA_PP_GANHO 3.0f
#define MISSIL_TEMPO_COMBUSTIVEL 2.0f

#define PASTA_ASSETS "assets/"
#define PASTA_DATA "assets/data/"
#define PASTA_IMAGES "assets/images/"
#define PASTA_SCREENSHOTS "assets/screenshots/"

#define ARQUIVO_SCOREBOARD "assets/data/scoreboard.dat"
#define ARQUIVO_STATS "assets/data/stats.dat"
#define ARQUIVO_SETTINGS "assets/data/settings.dat"

#endif
